export const colors = {
  background: "rgb(var(--mobile-background))",
  surface: "rgb(var(--mobile-surface))",
  card: "rgb(var(--mobile-card))",
  border: "rgb(var(--mobile-border))",
  textPrimary: "rgb(var(--mobile-text-primary))",
  textSecondary: "rgb(var(--mobile-text-secondary))",
  textMuted: "rgb(var(--mobile-text-muted))",
  accent: "rgb(var(--mobile-accent))",
  accentSoft: "rgb(var(--mobile-accent-soft))",
  accentBorder: "rgb(var(--mobile-accent-border))",
  successSoft: "rgb(var(--mobile-success-soft))",
  successBorder: "rgb(var(--mobile-success-border))",
  successText: "rgb(var(--mobile-success-text))",
  danger: "rgb(var(--mobile-danger))",
} as const;
